### ISSUE TITLE
redshift_subnet_group_name count cannot be determined on apply

### ISSUE THREAD

**Issue by syst0m** [terraform-aws-modules/terraform-aws-redshift#40]
Using the example produces an error on terraform apply, where the `redshift_subnet_group` has already been created by the redshift module, 
and then subsequent creation of the subnet group by the vpc module fails.

After uncommenting the `redshift_subnet_group_name = module.vpc.redshift_subnet_group` I get the following error on apply:
```
Error: Invalid count argument

  on .terraform/modules/ume-redshift/terraform-aws-redshift-2.5.0/main.tf line 111, in resource "aws_redshift_subnet_group" "this":
 111:   count = var.redshift_subnet_group_name == "" ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

The only way I have gotten this to work is by specifying `  create_redshift_subnet_group = false` in the vpc module instantiation.
The commit that introduces the option to copy snapshots to a different region (#24) comments out the `redshift_subnet_group_name` bit in the example, but there's no comment as to why this is the case.

**Comment by bryantbiggs** [comment]
the conflict is due to the VPC module and the Redshift module both creating a subnet group named the same which is a conflict. You can:
- Elect for either the VPC or Redshift module to create the subnet group (only one DB subnet group is created)
- Elect to use different names which will avoid the conflict (two DB subnet groups will be created)
